### ISSUE TITLE
Drag and drop activity and create new activity dragging mouse over cell

### ISSUE THREAD

**Issue by spiazzi** [thegrubbsian/jquery.ganttView#1]
Hi,

very nice work.
I think that could be very interessing if was possible to move activity  drag and drop it.
And also the possibility of create new activity selecting a number of cells.

**Comment by spiazzi** [comment]
Hi try to add this line in example script adding jquery ui:

```
            $(".ganttview-grid-row").selectable();
```

This permit to select the cell in the row.

**Comment by spiazzi** [comment]
Also trying:

```
$(".ganttview-block").draggable({ snap: '.ganttview-block-container' });
```

Seems to be quite dragabble.
What do you think?

**Comment by thegrubbsian** [comment]
Looks good to me...if you want to implement it and send me a pull request I'd be happy to integrate it.  We'll need to find some way to get the changed values back out either via some callback or some other API that allows the calling code to inspect the current state of the blocks.

**Comment by thegrubbsian** [comment]
I've added basic dragging and resizing support including callbacks that supply the new data for the block.  I don't think I'll build in support directly for adding a new item, but perhaps a feature to allow the data to be reloaded within the current instance to avoid a complete refresh of the DOM fragment.
