### ISSUE TITLE
Vertical scroll change

### ISSUE THREAD

**Issue by pranee758** [thegrubbsian/jquery.ganttView#16]
Vertical scroll change of the events is very urgent . please help me.............

**Comment by thegrubbsian** [comment]
Can you be more specific?

**Comment by pranee758** [comment]
I can be able to re-order the events in the gantt chart in vertical direction....Plz help me...........

**Comment by pranee758** [comment]
Along with the existing gantt chart i can be able to do that re-ordering

**Comment by thegrubbsian** [comment]
It will probably a while before I'll be able to get to this, my work schedule is quite full.

**Comment by lutze** [comment]
Vertical scrolling: Please see #14 

Reordering events: The chart takes a list `ganttData`, which has the following structure:

```
var ganttData = [
    {
        item 1
    }
    ...
    {
        item n
    }
]
```

You'll notice that ganttData is a list, which has order. In you'd like to change the vertical sorting of the chart, simply modify the sort when you build your ganttData list.
