### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by omerx** [thegrubbsian/jquery.ganttView#17]
Hello,

Could you please advice if it is possible to add time line under day line on the Gantt as seen on my attached chart? Or is there any sample similiar to this in jquery? If so can you please send ? I am looking for a week. Thank you in advance. 

Sample:
http://c1110.hizliresim.com/11/10/5/10019.jpg

**Comment by lutze** [comment]
It's been 3 years since this so I'm assuming the specific issue has already been solved. 

@omerx if you can provide a new link to the image (it's broken at the moment), I could possibly provide that advise. Let me know and we can reopen the issue and have a look.
