### ISSUE TITLE
toolstip to add information to the task

### ISSUE THREAD

**Issue by oskarcalvo** [thegrubbsian/jquery.ganttView#2]
I think that add a roll-over tools-tips can be great to know about the task or the event.

Oskar

**Comment by thegrubbsian** [comment]
This should be pretty easy to add using one of the many jQuery tooltip plugins like Tipsy or qTip.  I don't think it belongs directly in the ganttView plugin but rather something developers should add themselves within their application.  There is very basic support for title attributes on the gantt blocks which provides some sort of tooltip.
