### ISSUE TITLE
activity with time

### ISSUE THREAD

**Issue by ricardovoigt** [thegrubbsian/jquery.ganttView#22]
There is the possibility of placing two activities the same day, one starting from 08:00 to 12:00 and another from 13:30 to 18:00 for example?

Its ignoring Saturdays and Sundays? Some property?

**Comment by lutze** [comment]
As is demonstrated [here](http://thegrubbsian.github.io/jquery.ganttView/example/index.html), multiple activities can currently be given the same day. 

Right now, the plug-in doesn't support hourly resolution, only Day/Month. We're looking to expand that, which could provide the support requested.

**Comment by kobruleht** [comment]
You can use https://github.com/GuillaumeSmaha/jquery.ganttView for for this as discussed in https://github.com/thegrubbsian/jquery.ganttView/pull/26

**Comment by lutze** [comment]
Should be solved with merged solution from 0.8.9-dev-pull-3 (or 2, wherever that was) tracked through #26  as @kobruleht mentions. Day late and a dollar short, but I'm bringing some of these up-to-snuff over the next two weeks to clean up this backlog. So, the current 0.8.9-dev has a version of multi-line support I haven't tested fully yet. I'll check it this week and tune anything up that needs be.
