### ISSUE TITLE
live() is a deprecated function (from 1.7+) and removed completely from jQuery 1.9+.

### ISSUE THREAD

**Issue by sanchan** [thegrubbsian/jquery.ganttView#27]
So, it doesn't work with 1.9+.

Replacing this live() here:
https://github.com/thegrubbsian/jquery.ganttView/blob/master/jquery.ganttView.js#L283

for .on(), it works again (tested here with jQuery v1.9.1).

btw, thanks for your work :D

**Comment by dmr** [comment]
You can checkout my branch: https://github.com/dmr/jquery.ganttView

Working with a recent jquery version

**Comment by lutze** [comment]
@dmr Would you mind creating a pull request? I'd like to merge the change from your .js file and track the change as coming from your fork in the network graph.

**Comment by dmr** [comment]
@lutze sure, https://github.com/thegrubbsian/jquery.ganttView/pull/30 :)

**Comment by lutze** [comment]
@dmr would you mind rebranching and just submitting the pull request with the individual change to `jquery.ganttview.js`? I don't want to change file hosting or move data around and such. 

Or if it's not worth the bother I'll just make the change in the branch.
