### ISSUE TITLE
Project activity

### ISSUE THREAD

**Issue by dmr** [thegrubbsian/jquery.ganttView#28]
I see 125 forks of this project but no change in the main repository in the last 3 years.
Is there anyone still developing on this project?

If not, which of the forks is still being developed?

**Comment by usmonster** [comment]
[@taitems/jQuery.Gantt](https://github.com/taitems/jQuery.Gantt) is a pretty active fork-of-a-fork of this.

**Comment by dmr** [comment]
Thanks!
