### ISSUE TITLE
bootstrap css fix

### ISSUE THREAD

**Issue by ilidio** [thegrubbsian/jquery.ganttView#29]
I had a problem using jQuery.ganttView, with bootstrap and I had some CSS problems.

I had to fix it.... And the CSS fix is :

< style >
/\* bootstrap css fix - begin */
    #ganttChart div,
    #ganttChart div:before,
    #ganttChart div:after {
      -webkit-box-sizing: initial;
         -moz-box-sizing: initial;
              box-sizing: initial;
    }
< /style >

<br/><br/>
When you use ...
< div id="ganttChart" > < /div >

< script >
    $(function () {
            $("#ganttChart").ganttView({  ...
                         ...
< /script >

**Comment by ilidio** [comment]
The problem of bootstrap was the following CSS lines:

*,
*:before,
*:after {
         -webkit-box-sizing: border-box;
         -moz-box-sizing: border-box;
          box-sizing: border-box;
}

These CSS lines breaks jquery.ganttView layout. So you have only have to reset.

**Comment by lutze** [comment]
Are those lines part of the bootstrap CSS?

**Comment by ilidio** [comment]
Yes, they belong to bootstrap.
<b>Example:</b>
https://www.dropbox.com/s/vp8d4bcr264viwo/bootstrap.css
     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <i> (Line : 264)</i>

<br/>
<b>Download:</b>
http://getbootstrap.com/getting-started/#download

**Comment by lutze** [comment]
Ok. I updated the css [here](https://github.com/thegrubbsian/jquery.ganttView/blob/0.8.9-dev/jquery.ganttView.css), please have a look and let me know if that implements the fix for you.

**Comment by ilidio** [comment]
Yes, that fix works for me. I just test it yesterday.

Thanks for the reply

**Comment by lutze** [comment]
Glad to, thanks for the ticket.
