### ISSUE TITLE
X-axis in numbers?

### ISSUE THREAD

**Issue by gkakasevski** [thegrubbsian/jquery.ganttView#34]
Hi, I don't want to use X-axis in days/months, but in numbers, for example, starting from 0, 1, 2, 3... up to 100. Can I do this with your library, or can you suggest me another one in which I can do this?

**Comment by lutze** [comment]
Hi,

So, this tool produces Gantt charts, and as such is designed to work with start/end dates for items in the data object given to it. You could modify this, but I don't think it's something we'll look at adding. 

You might try looking at D3.js as a visualization-construction library for what you want to do. It takes a bit to learn but is quite usable and will make what you're looking to do a piece of cake.
