### ISSUE TITLE
More item in row

### ISSUE THREAD

**Issue by atomjani** [thegrubbsian/jquery.ganttView#35]
I like more dev stages in one row. Because they get less place. I can use more color.
Example:
{ name: "Feature1", start: new Date(2010,00,01), end: new Date(2010,00,03), color: "#f0f0f0", start: new Date(2010,00,04), end: new Date(2010,00,08), color: "#fcf0f0" },

**Comment by lutze** [comment]
Hi @atomjani, there's a feature request in the pipeline to help with this. I'll refer this there for the time being.

**Comment by lutze** [comment]
Refer to work on #26 for future support on the request. Thanks!
