### ISSUE TITLE
Display the gantt chart in weeks than days

### ISSUE THREAD

**Issue by Tekm1** [thegrubbsian/jquery.ganttView#36]
I'm working on it but i don't make any progress, i'd like to ask if the documentation is coming or not and if there's an easy way to do my modification.

Thank you for your work.

**Comment by lutze** [comment]
Hi @Tekm1, 

Thanks for the request and sorry that it's not been resolved yet. There's a pull request that I'm using to track getting this supported -- if you would, please refer to #26 for updates as to how that's going.
