### ISSUE TITLE
IE7 CSS

### ISSUE THREAD

**Issue by babar45** [thegrubbsian/jquery.ganttView#4]
hello,

for jquery.ganttView.css

div.ganttview-slide-container {
    position: relative;
    overflow : auto;
    border-left: 1px solid #999;
}

div.ganttview-blocks {
    position: absolute;
    top: 40px;
    left : 0px; 
}

and for jquery.ganttView.js
insert after "container.css("width", (w + 2) + "px");"

var h = jQuery("div.ganttview-slide-container", container).outerHeight();
slideDiv.css("height", (h + 20) + "px");

**Comment by thegrubbsian** [comment]
Could you please fork and send me a pull request...it's easier than trying to merge in code fragments like this.
