### ISSUE TITLE
how to generate datetime data from php

### ISSUE THREAD

**Issue by krissanawat** [thegrubbsian/jquery.ganttView#44]
I try 

```
 foreach ($activity as $key => $activity):
            $data[$key]['id'] = $activity->id;
            $data[$key]['name'] = $activity->name;
            foreach($activity->task as $key2 => $task):
                $data[$key]['series'][$key2]['name'] = $task->name;
                $data[$key]['series'][$key2]['start']  =  date( 'D M d Y H:i:s',strtotime($task->start_time)).' GMT+0700 (SE Asia Standard Time)';
                $data[$key]['series'][$key2]['end']  = date( 'D M d Y H:i:s',strtotime($task->stop_time)).' GMT+0700 (SE Asia Standard Time)';
            endforeach;
        endforeach;
```

got it
![](http://i.imgur.com/C18LQio.png)

thank for answer

**Comment by lutze** [comment]
Hi there, 

Does your console provide a column # for the error? I'm not exactly sure but it looks like, in the previous line, minStart is being set to undefined. This could mean that you're not correctly building a date object in your PHP code. 

Something to try: in the javascript, in the `for (var j` statement, after you define `var start=`, print `minStart` and `start` to the console and compare what's coming out. 

If we're seeing start = undefined, then you'll need to look at how you're building your data object to make sure there isn't an error in your date function for the `[$key2]['start']` line.

**Comment by lutze** [comment]
I'm closing this because there wasn't anything back on it. If you're still having issues or would like to discuss it further please let me know.
