### ISSUE TITLE
bars are positioned incorrectly under bootstarp 3

### ISSUE THREAD

**Issue by kobruleht** [thegrubbsian/jquery.ganttView#46]
If used under bootstrap 3, bar horizontal and vertical positions are incorrect by some pixels.

reset.css does not fix this.

Using

```
    * {
        box-sizing: content-box;
    }
```

fixes this but it breaks bootstrap layout.

**Comment by pvdoenuf** [comment]
Es sencillo, si tu contenedor para el ganttview tiene la clase o el id 'gantt' en la hoja de estilos lo pones así:
.gantt *{
    box-sizing: content-box;
}

Para que afecte solo a lo contenido en ese div.

My english is quite poor, but:
It's simple, if your container (usually a div) has a class or id 'gantt', for example, in your stylesheet you just need to add:
.gantt *{
    box-sizing: content-box;
}
By this way de content-box only applies inside the div gantt.
