### ISSUE TITLE
Click on empty cell is not captured

### ISSUE THREAD

**Issue by kobruleht** [thegrubbsian/jquery.ganttView#47]
It is not possible to add new bar by clicking in empty cell.
onClick event does not file since it is bound to bar using div.ganttview-block

Some event with clicked empty bar coordinates shoudl also fire if clicked outside bar

If gantt fork from  https://github.com/GuillaumeSmaha/jquery.ganttView is used, this allows to implement online booking system where bookings can placed by clicking in empty cell.

How to change code so that click in empty cells can captured ?

**Comment by lutze** [comment]
There isn't currently a function to catch onClick in a background cell. 

So, you'd theoretically want to add a function call to the setup javascript, that selected all items with `class=ganttview-grid-row-cell` and set `.on(click, your-booking-function-launcher)`. This would maybe do what you're looking for? 

It's an interesting idea -- most implementations I've seen are just visualizations. I'm going to add support for an optional grid-block onClick to v0.9.0.
