### ISSUE TITLE
FullCalendar API

### ISSUE THREAD

**Issue by ari** [thegrubbsian/jquery.ganttView#6]
Nice work on this project.

I'd like to ask that you examine a similar project ( http://arshaw.com/fullcalendar/ ) which does not have a gantt option, but does deal with similar scheduling data. It is a very popular project and used widely, so it would be extremely helpful if your code implemented a similar or identical API, particularly for the definition of json event data but also for other functions.

I've implemented fullcalendar in an open source project management system and am looking to add your implementation to that as well. Initially, I was hoping to add gantt as a plugin to fullcalendar but lacked the time (or CSS skills) to pursue that. (http://code.google.com/p/fullcalendar/issues/detail?id=150 )

Anyhow, thanks again, if I extend your code I'll certainly fork and contribute it back here. 

Ari Maniatis
http://github.com/ari/clockingit/

**Comment by vnehess** [comment]
Great idea to merge this cool plugin to be a view in fullcalendar, i will be looking at this in the next few weeks.

**Comment by omerx** [comment]
Great idea. I'm using fullcalendar. Fullcalendar a very good script.

**Comment by ari** [comment]
There has already been some recent work in full calendar to implement a 'resources view' which is very similar to a gantt chart provided by this script. Hopefully it will be polished and ready for use over the next few months.
