### ISSUE TITLE
Conflick with BootStrap

### ISSUE THREAD

**Issue by walt1992** [thegrubbsian/jquery.ganttView#68]
When I use your API with BootStrap, I guess It makes some conflict.

![conflict](https://user-images.githubusercontent.com/37332261/41227422-a4e924aa-6daf-11e8-9113-6f4ab9ffd6f7.PNG)

 First, the block size is not same with cell's. Also, When I resize blocks, Its height getting thinner.

most of all, the whole ganttChart is broken.

**Comment by lutze** [comment]
Unfortunately, the package isn't currently tested or certified to any modern versions of Bootstrap and will be a "use at your own peril" sort of situation. If you find any fixes or more specific issues (my guess from the screenshot would be something in the CSS in bootstrap is overwriting the CSS in ganttView) please add them or submit pull requests for the community to review
