### ISSUE TITLE
Add info before calendar

### ISSUE THREAD

**Issue by allefgomes** [thegrubbsian/jquery.ganttView#71]
How can I add new lines before calendar? For example:

`id: 1, name: "Name 1", desc: "Description 1", user: "Allef Gomes",  series: [
      { name: "planejado", start: Date.today, end: Date.today + 5 },
      { name: "executado", start: Date.today, end: Date.today + 3, color: "#f0f0f0" }
  ]`

In this case I added description and user.

Thanks.

**Comment by Tulasi59** [comment]
Please add the info what you required to InputDict
InputDict = {id: 1, name: "Name 1", desc: "Description 1", user: "Allef Gomes", series: [ { name: "planejado", start: Date.today, end: Date.today + 5 }, { name: "executado", start: Date.today, end: Date.today + 3, color: "#f0f0f0" } ]}
Then, add the data in  jquery.ganttView.js line num :148

For Example:

 var seriesDiv = jQuery("<div>", { "class": "ganttview-vtheader-series" });
                var sch_info_Div = jQuery("<div>", { "class": "ganttview-vtheader-sch_info" });
                var lockDiv = jQuery("<div>", { "class": "ganttview-vtheader-lock" });

                for (var j = 0; j < data[i].series.length; j++) {
                    seriesDiv.append(jQuery("<div>", { "class": "ganttview-vtheader-series-name" })
                        .append(data[i].series[j].name));

                     sch_info_Div.append(jQuery("<div>", { "class": "ganttview-vtheader-sch_info-name" })
                        .append(data[i].desc));
                     lockDiv.append(jQuery("<div>", { "class": "ganttview-vtheader-lock-name" })
                        .append(data[i].user));
                }
                itemDiv.append(seriesDiv);
                itemDiv.append(sch_info_Div);
                 itemDiv.append(lockDiv);
                headerDiv.append(itemDiv)

**Comment by allefgomes** [comment]
Thanks so much.
