### ISSUE TITLE
Readonly activities

### ISSUE THREAD

**Issue by johncardozo** [thegrubbsian/jquery.ganttView#73]
Hi,
is there any chance to set the activities read only?
I want to use the component to show information but I don't want the user update the activities using this component.
Thanks for your help

**Comment by lutze** [comment]
Hi, this would be something that you'd need to consider in how you write update methods in your code. You could for example include a conditional check for a certain user property, like an admin right. 

Or, if you just want it to only ever be a tool for drawing charts but not editing them, easiest will be to not implement the onResize / onDrag / onClick methods.
