### ISSUE TITLE
gap in series cause bad CSS 

### ISSUE THREAD

**Issue by linquant** [thegrubbsian/jquery.ganttView#74]
https://github.com/thegrubbsian/jquery.ganttView/blob/0241f4dabca9b0be76888f7c37feaeb8ecbbf8f2/jquery.ganttView.css#L93

Width: 21px or 20px ?

div.ganttview-grid-row-cell {
	width: 21px;
	height: 31px;
	border-right: 1px solid #f0f0f0;
	border-top: 1px solid #f0f0f0;
}

**Comment by linquant** [comment]
Or here

      https://github.com/thegrubbsian/jquery.ganttView/blob/0241f4dabca9b0be76888f7c37feaeb8ecbbf8f2/jquery.ganttView.js#L46

**Comment by lutze** [comment]
Cleaning up some old issues, if this is still something bugging you could you please reopen the issue and describe an action you're hoping we can take with the package?
