### ISSUE TITLE
CSS Fix

### ISSUE THREAD

**Issue by ryancollingwood** [thegrubbsian/jquery.ganttView#9]
More of a patch than a bug fix, to correct series being affected from inherited CSS text aligns.

div.ganttview-block-container {
    height: 28px;
    padding-top: 4px;
    text-align: left;  
}

Spent a day pulling my hair out!

**Comment by lutze** [comment]
Makes sense as a default state for the plugin, particularly to avoid unintentional text effects. I've added it to the new dev branch.
